#!/usr/bin/env bash
# Hermes VPS bootstrap — one-shot deploy to an Ubuntu VPS.
#
# Usage (on the VPS, as root):
#   wget -qO /tmp/bootstrap.sh https://raw.githubusercontent.com/ramana-gottipati/hermes/main/scripts/vps-bootstrap.sh
#   bash /tmp/bootstrap.sh
#
# Idempotent: safe to re-run. Existing /opt/hermes is moved aside, not deleted.

set -euo pipefail

REPO="https://github.com/ramana-gottipati/hermes.git"
TARGET="/opt/hermes"
SERVICE="hermes-telegram"

echo ""
echo "============================================================"
echo " Hermes VPS Bootstrap"
echo "============================================================"
echo ""

# --- 1. Stop any previous service ------------------------------------------
if systemctl list-unit-files | grep -q "^${SERVICE}.service"; then
    echo "==> Stopping existing ${SERVICE} service"
    systemctl stop "${SERVICE}.service" 2>/dev/null || true
fi

# --- 2. Set aside any previous install --------------------------------------
if [ -d "${TARGET}" ]; then
    BACKUP="/opt/hermes-old-$(date +%s)"
    echo "==> Moving previous ${TARGET} to ${BACKUP}"
    mv "${TARGET}" "${BACKUP}"
fi

# --- 3. Install OS prerequisites (idempotent) ------------------------------
echo "==> Installing system packages (python3, pip, venv, git, sqlite3)"
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv git curl sqlite3 >/dev/null

# --- 4. Clone fresh from GitHub --------------------------------------------
echo "==> Cloning Hermes from ${REPO}"
git clone --quiet "${REPO}" "${TARGET}"
cd "${TARGET}"

# --- 5. Python venv + deps --------------------------------------------------
echo "==> Creating Python venv and installing dependencies"
python3 -m venv .venv
# shellcheck disable=SC1091
source .venv/bin/activate
pip install --upgrade pip --quiet
pip install -r requirements.txt --quiet

# --- 6. Collect secrets and write .env -------------------------------------
echo ""
echo "------------------------------------------------------------"
echo " Now paste your three secrets when prompted."
echo " They'll be written to ${TARGET}/.env (mode 600, owner root)."
echo "------------------------------------------------------------"
echo ""
read -r -p "Anthropic API key (starts with sk-ant-): " ANTHROPIC_KEY
echo ""
read -r -p "Telegram bot token (8802281704:...): " TG_TOKEN
echo ""
read -r -p "Your Telegram user ID (the number, e.g. 282907906): " TG_USER
echo ""

cat > "${TARGET}/.env" <<EOF
# Generated by vps-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
HERMES_DEFAULT_MODEL=claude-sonnet-4-6
HERMES_FAST_MODEL=claude-haiku-4-5
HERMES_HOST=0.0.0.0
HERMES_PORT=8000
HERMES_LOG_LEVEL=INFO
TELEGRAM_BOT_TOKEN=${TG_TOKEN}
TELEGRAM_ALLOWED_USER_IDS=${TG_USER}
TRADING_LIVE=false
BROKER_API_KEY=
BROKER_API_SECRET=
DATABASE_URL=sqlite:///./data/hermes.db
EOF
chmod 600 "${TARGET}/.env"

# --- 7. systemd service for 24/7 operation ---------------------------------
echo "==> Installing systemd unit ${SERVICE}.service"
cat > "/etc/systemd/system/${SERVICE}.service" <<EOF
[Unit]
Description=Hermes Telegram Bot
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=${TARGET}
ExecStart=${TARGET}/.venv/bin/python -m src.assistant.telegram_bot
Restart=on-failure
RestartSec=5
StandardOutput=append:/var/log/hermes-telegram.log
StandardError=append:/var/log/hermes-telegram.log

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --quiet "${SERVICE}.service"
systemctl start "${SERVICE}.service"

sleep 3

# --- 8. Report ---------------------------------------------------------------
echo ""
echo "============================================================"
echo " Status check"
echo "============================================================"
systemctl status "${SERVICE}.service" --no-pager | head -12
echo ""
echo "============================================================"
echo " Done."
echo "------------------------------------------------------------"
echo " Bot is now running 24/7. It will survive reboots."
echo ""
echo " Live logs:    journalctl -u ${SERVICE} -f"
echo " Status:       systemctl status ${SERVICE}"
echo " Restart:      systemctl restart ${SERVICE}"
echo " Stop:         systemctl stop ${SERVICE}"
echo ""
echo " Test it now — message @ramana_hermes_bot from your phone."
echo "============================================================"
echo ""
